### PR TITLE
test and fix for serializing DateAndTime with julianDayOffset

### PR DESCRIPTION
**Pull request by MarcusDenker**
- add test testSerializationDateAndTime2
- use julianDayNumberUTC to serialize

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Very strange: if I run the test locally, it is green. I even created a complete new image (Pharo11), loaded the branch, ran tests: green

**Comment by MarcusDenker** [comment]
```
SoilPrimitiveSerializationTest
 ✗ #testSerializationDateAndTime2 (5ms)
TestFailure: Got #[29 5 211 224 2 0 0 5 0] instead of #[29 5 210 224 2 224 234 4 0 5 120].
```

**Comment by MarcusDenker** [comment]
ahh... we can not hard-code the date

**Comment by MarcusDenker** [comment]
Fails with:

```
SoilPrimitiveSerializationTest
 ✗ #testSerializationDateAndTime2 (5ms)
TestFailure: Got #[29 5 211 224 2 0 0 5 0] instead of #[29 5 210 224 2 224 234 4 0 5 120].
```

**Review by noha — APPROVED** [review]

**Pull request merged**
