### PR TITLE
Comments and trivial cleans

### PR DESCRIPTION
**Pull request by MarcusDenker**
- add comments
- use #== to compare classes in SoilObjectId>>#= (saves one message send)
- simplify SoilIndexedDictionary #removeKey:ifAbsent:

### CODE REVIEW

**Review by noha — APPROVED** [review]

**Comment by MarcusDenker** [comment]
Pharo 12 failure is tracked here: https://github.com/hpi-swa/smalltalkCI/issues/622

**Comment by MarcusDenker** [comment]
Now it fails with

```
Testing project...
Instance of MetacelloProjectRegistration did not understand #currentlyLoadedClassesInProject
```

**Comment by MarcusDenker** [comment]
I opened an issue for Pharo12: https://github.com/pharo-project/pharo/issues/15939

**Comment by MarcusDenker** [comment]
And it fails not always. Which means that this is the result of the new test order randomization in Pharo12... I guess another test changes the encode and does not change it back to the default.

**Review by noha — APPROVED** [review]

**Pull request merged**
